/**
 * Shared source of the hero dog's frame URLs — imported by both the
 * Preloader (so they're fetched/decoded before the site is shown, instead
 * of streaming in after) and HeroDogFrames.tsx (the canvas renderer that
 * draws them). Keeping this in one module means both sides reference the
 * exact same glob results, so whatever the Preloader fetches is the exact
 * same cached resource HeroDogFrames then draws from — no duplicate
 * network requests.
 *
 * 146 evenly-spaced (denser near the loop seam) frames extracted from the
 * directional dog video (src/assets/new-hero-bg-video-24fps.mp4), plus a
 * dedicated center.webp for the direct-gaze pose. Generated by
 * scripts/extract-dog-frames.mjs — re-run that script if the source video
 * changes. Sorted alphabetically, which matches temporal frame order since
 * filenames are zero-padded.
 */
const frameModules = import.meta.glob('../assets/hero-dog-frames/frames/frame-*.webp', {
  eager: true,
  query: '?url',
  import: 'default',
}) as Record<string, string>
export const FRAME_URLS = Object.keys(frameModules)
  .sort()
  .map((k) => frameModules[k])

const centerModule = import.meta.glob('../assets/hero-dog-frames/frames/center.webp', {
  eager: true,
  query: '?url',
  import: 'default',
}) as Record<string, string>
export const CENTER_URL = Object.values(centerModule)[0] as string | undefined

export const TOTAL = FRAME_URLS.length
export const hasFrames = TOTAL > 0 && !!CENTER_URL

/** Every hero dog frame URL, center first since it's needed the instant the hero paints. */
export function allHeroDogFrameUrls(): string[] {
  return CENTER_URL ? [CENTER_URL, ...FRAME_URLS] : [...FRAME_URLS]
}
